config/routes.rb
require 'sidekiq/web'
require 'split/dashboard'

Upandsell::Application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe'
  get '/users/auth/mailchimp/callback' => 'user/settings/integrations#create'
  get '/users/auth/createsend/callback' => 'user/settings/integrations#create'

  get '/auth/paypal' => 'user/settings/payments#paypal_connect', as: 'paypal_integration'
  get '/auth/paypal/callback' => 'user/settings/payments#paypal_callback', as: 'paypal_integration_callback'

  devise_for :users, controllers: {  omniauth_callbacks: 'omniauth_callbacks',
    confirmations: 'confirmations', registrations: "registrations" }

    devise_scope :user do
      delete "/logout" => "devise/sessions#destroy"
      get "/join"   => "registrations#new"
      get "/login" => "devise/sessions#new"
    end
 # Front-end
 root 'landing#index'
 get 'no-beta' => 'landing#beta'
 post 'beta_request' => 'landing#beta_request'
 get 'pricing' => 'site#pricing'
 get 'privacy' => 'site#privacy'
 get 'terms' => 'site#terms'
 get 'demo' => 'site#demo'

 # subscriptions emails
 get 'unsubscribe/u/:user/:type/:signature' => 'emails#unsubscribe_user',
 :as => 'unsubscribe_user'
 get 'confirm_unsubscribe/u/:user/:type/:signature' => 'emails#confirm_unsubscribe_user',
 :as => 'confirm_unsubscribe_user'
 get 'unsubscribe/o/:order/:signature' => 'emails#unsubscribe_order',
 :as => 'unsubscribe_order'
 get 'confirm_unsubscribe/o/:order/:signature' => 'emails#confirm_unsubscribe_order',
 :as => 'confirm_unsubscribe_order'
 get 'unsubscribed' => 'emails#unsubscribed'

  #product page
  get '/p/:slug' => 'products#show', :as => 'product_slug'

  #checkout
  post 'checkout/paypal' => 'checkouts#paypal'
  get 'checkout/pay_info' => 'checkouts#pay_info'
  get 'checkout/braintree_token' => 'checkouts#braintree_token'
  post 'checkout/pay' => 'checkouts#pay'
  post 'checkout/unsubscribe_order_updates' => 'checkouts#unsubscribe_order_updates'
  get 'checkout/check_payment' => 'checkouts#check_paypal_payment'
  post 'checkout/ipn' => 'checkouts#ipn'
  get 'download/p/:token' => 'checkouts#download', :as => 'download_product'
  post 'checkout/check_coupon' => 'checkouts#check_coupon'

  resources :products, only: [:show]  do
  #get 'paypal',  on: :member
end

namespace :user do
  root 'dashboard#index'
  post 'dashboard/to_admin' => 'dashboard#to_admin'
  get 'dashboard/metrics'  => 'dashboard#metrics'
  get 'dashboard/onload_metrics'  => 'dashboard#onload_metrics'
  get 'complete_signup' => 'settings/billings#new'

  resources :affiliations
  resources :products, except: [:show] do
    post 'upload'
    get 'toggle_published',  on: :member
    get 'share', on: :member
  end

  resources :orders, only: [:index] do
   get 'refund', on: :member
 end

 namespace :tools do
  resources :coupons, except: [:new]
  resources :serial_keys, except: [:new]
  resources :mailing_lists do
    get 'sync', on: :member
    get 'createsend_clients', on: :collection
    get 'createsend_lists', on: :collection
    post 'create_sync', on: :member
    post 'remove_sync', on: :member
    get 'search', on: :collection
    post 'send_email', on: :member
    post 'send_test_email', on: :member
    resource :emails
  end
end


get 'setup', to: 'setup#index'
get 'billing_details', to: 'setup#billing_details'
post 'billing_details', to: 'setup#save_billing_details'
get 'resend_email', to: 'setup#resend_email'
patch 'update_email', to: 'setup#update_email'

post 'products/files'  => 'products#files'

namespace :settings do
  resources :webhooks, except: [:new]
  resource :account, only: [:edit, :update]
  resource :payments, only: [:edit, :update] do
    get 'connect'
    get 'connect_callback'
  end
  resource :integrations, only: [:edit, :create]
  resource :emails, only: [:edit, :update]
  resource :billing, except: [:index] do
    get 'invoice/:id', to: 'billings#invoice', as: 'invoice_download'
    post 'apply_coupon'
  end
end
end
namespace :admin do
 mount Sidekiq::Web => 'sidekiq'

 root 'dashboard#index'
 resources :users, only: [:index,:show] do
  post 'switch'
end
resources :products, only: [:index,:show, :destroy]
resources :orders, only: [:index,:show]
resources :invoices, only: [:index,:show]

resources :emails, only: [:index, :create] do
  get 'send_test_email'
end
resources :affiliations, only: [:index]
end

match "/admin/split" => Split::Dashboard, :anchor => false, :via => [:get, :post], :constraints => lambda { |request|
  request.env['warden'].authenticated? # are we authenticated?
  request.env['warden'].authenticate! # authenticate if not already
  request.env['warden'].user.admin?
}

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def index
    @products = Product.all.page(params[:page]).per(8)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  include SignInAs

  def index
    @users = User.all.page(params[:page]).per(15)
  end

  def switch
   sign_in :user, User.find(params[:user_id])
   self.remember_admin_id(current_user.id)
   redirect_to user_root_path
 end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CheckoutSession
  include CheckoutProduct

  skip_after_filter :intercom_rails_auto_include
  layout "product"

  def show
    @product = Product.find_by_slug!(params[:slug])
    set_landing_env
    register_visit(@product)
    @user = User.find(@product.user_id)
    set_user_env
    return if !@published
    @coupons = !@product.coupons.active.not_expired.blank?
    #registra pagamento paypal se presente
    return if params[:payKey] && register_paypal_payment(params[:payKey])
    #check sessione se il prodotto risulta gia' acquistato
    set_download_product_env if is_user_product?(@product.id)
  end

  private
  def set_landing_env
    @downloads = 0
    @download_url = '#'
    @accept_marketing = true
    @token = nil
    @title = @product.name
  end

  def set_user_env
    @paypal = @user.paypal_active?
    @ga_code = @user.ga_code
    @credit_card = @user.credit_card_active?
    @published = true if (@paypal || @credit_card) && @product.published && @user.subscribed?
  end

  private
  def set_download_product_env
    order = Order.where(token: session[:user_products][@product.id]).first
    if order.present? && order.status == 'completed'
      @downloads =  order.n_downloads
      @action = 'download' if (@downloads < 5)
      @downloadable = true if (@downloads < 5)
      @token = order.token
      @accept_marketing = order.buyer_accepts_marketing
      @download_url = download_product_url(order.token)
    end
  end

  private
  def register_paypal_payment(pay_key)
    order = Order.where( gateway_token: pay_key).first
    if order.status == 'completed' && order.product_id == @product.id
      update_user_products(order.product.id, order.token)
      @downloads =  order.n_downloads
      @action = 'afterPaypal'
      @downloadable = true if (@downloads < 5)
      @token = order.token
      @accept_marketing = order.buyer_accepts_marketing
      @download_url = download_product_url(order.token)
      return true
    end
    false
  end

  private
  def download_url(pay_key)
    order = Order.where(gateway_token: pay_key)
    product = Product.find(order: product_id)
    return product_slug_url(slug: product.slug, payKey: pay_key)
  end

  def payment_completed?(pay_key)
   order = Order.where( gateway_token: pay_key)
   if order and order.status == 'completed'
     return true
   end
   return false
 end
end

app/controllers/user/affiliations_controller.rb
class User::AffiliationsController < User::BaseController

  def index
  end

end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_filter :authenticate_user!
  layout 'application'
  include SignInAs

  before_action :was_admin

  def was_admin
    @was_admin = self.remember_admin_id?
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < User::BaseController
  include SignInAs
  def index
    if current_user.currency == 'USD'
      @currency = '$'
    elsif current_user.currency == 'GBP'
      @currency = '£'
    else
      @currency = '€'
    end
  end

  def to_admin
   sign_in :user, User.find(self.admin_id)
   self.clear_remembered_admin_id
   redirect_to admin_root_path
 end

 def onload_metrics
  products = current_user.products
  demo = false
  visits = Metric::Product.new(products).visits(1.days.ago, :hour).get
  sales = Metric::Product.new(products).sales(1.days.ago, :hour).exchange_to(current_user.currency.to_sym).get
  if sales[:sales] == 0
    js_data = demo_data(:day)
    demo = true
  else
    js_data = to_js(visits[:data].deep_merge(sales[:data]))
  end
  earnings = get_earnings(sales)

  render json: {demo: demo, graph_data: js_data, sales: sales[:sales], visits: visits[:visits], conversion_rate: conversion_rate(visits[:visits], sales[:sales]), earnings: earnings}
end

def metrics
  if params[:products] != '0'
    products = current_user.products.where(id: params[:products])
  else
    products = current_user.products
  end
  demo = false
  pd = :day
  if params[:period] == 'month'
    period = 30.days.ago
  elsif params[:period] == 'week'
    period = 7.days.ago
  else
    period = 1.days.ago
    pd = :hour
  end

  visits = Metric::Product.new(products).visits(period, pd).get
  sales = Metric::Product.new(products).sales(period, pd).exchange_to(current_user.currency.to_sym).get
  if  sales[:sales] == 0
    js_data = demo_data(params[:period].to_sym)
    demo = true
  else
    js_data = to_js(visits[:data].deep_merge(sales[:data]))
  end
  render json: {demo: true, graph_data: js_data, sales: sales[:sales],
    visits: visits[:visits], conversion_rate: conversion_rate(visits[:visits], sales[:sales])}
  end

  def demo_data(period)
    js_data = []
    if period == :day
      (1.days.ago.to_i .. Time.now.to_i).step(1.hour) do |date|
        js_data << {date: Time.at(date), sales: Random.rand(1000), earnings: Random.rand(2000), visits: Random.rand(4000)}
      end
    elsif period == :week
      (7.days.ago.to_i .. Time.now.to_i).step(1.day) do |date|
        js_data << {date: Time.at(date), sales: Random.rand(1000), earnings: Random.rand(2000), visits: Random.rand(4000)}
      end
    else
      (30.days.ago.to_i .. Time.now.to_i).step(1.day) do |date|
        js_data << {date: Time.at(date), sales: Random.rand(1000), earnings: Random.rand(2000), visits: Random.rand(4000)}
      end
    end
    js_data
  end
  def to_js(data)
    graph = []
    data.each do |day, values|
      graph << {day: day}.merge(values)
    end
    graph
  end
  private
  def get_earnings(sales, convert = true)
    earnings = {}
    earnings[:month] =  sales[:earnings]
    earnings[:week] = split_week(sales[:data])
    if  sales[:data][Time.zone.now.beginning_of_day]
      earnings[:today] =  sales[:data][Time.zone.now.beginning_of_day][:earnings]
    else
      earnings[:today] = 0
    end
    earnings.each {|k,v|
      if convert
        earnings[k] = Money.new(v, current_user.currency).cents
      end
    }
    earnings[:summary_data] = sales[:data]
    earnings
  end

  private
  def conversion_rate(visits, sales)
    return 0 if (visits == 0) || (sales == 0)
    ((sales.fdiv(visits)) * 100).round(2)
  end

  private
  def split_week(data)
    days = (7.days.ago..Time.zone.now.beginning_of_day)
    week = data.select {|k,v| days.cover?(k)}
    week.inject(0) do |sum, (k,v)|
      sum + v[:earnings]
    end
  end
end

app/controllers/user/mailing_lists_controller.rb
class User::MailingListsController < User::BaseController

  def create
    @list = MailingList.new
    @list.user_id = current_user.id
    Rails.logger.info params
    @list.name = params[:mailing_list][:name]
    @list.products = current_user.products.where(id: params[:mailing_list][:products]) || current_user.products
    @list.save

    redirect_to user_mailing_lists_path
  end

  def index
   @mailing_list = MailingList.new
   @list = MailingList.all
   render template: 'user/tools/newsletter'
 end

 def show
   render template: 'user/tools/newsletter_send'
 end

 def destroy
  MailingList.find(params[:id]).delete
  redirect_to user_mailing_lists_path
end

def update

end

def sync
end



end

app/controllers/user/orders_controller.rb
class User::OrdersController < User::BaseController

  def index
    if params[:products] && params[:products] != '0'
      @orders = current_user.orders.where(product_id: params[:products])
    else
      @orders = current_user.orders.order('created_at desc')
    end

    if params[:q] && !params[:q].blank?
      @orders = @orders.email_starts_with(params[:q])
    end

    @orders = @orders.completed.page(params[:page]).per(8)
  end

  def refund
    @order = Order.find(params[:id])
    if @order.user_id == current_user.id && @order.refund
      redirect_to user_orders_path, notice: 'Payment Refunded'
    else
     redirect_to user_orders_path, notice: 'Error, try from Gateway panel.'
     return
   end
 end
end

app/controllers/user/payments_controller.rb
class User::PaymentsController < User::BaseController
  include PayPal::SDK::AdaptivePayments
def index
@payments= Customer.find(current_customer.id).payment
.where(completed: true)

end

def refund
  @payment = Payment.find(params[:id])
   #Paypal logic
   paypal = PayPal::SDK::AdaptivePayments.new
   response = paypal.Refund( :payKey => @payment.paykey)

   print response
    render json: { pay_key: response}
end
end

app/controllers/user/products_controller.rb
class User::ProductsController < User::BaseController

  def index
    @products = current_user.products.page(params[:page]).per(6)
  end

  def new
  #  unless current_user.subscribed?
  #    redirect_to user_root_path
  #  end
    @product = Product.new
    @product.price_currency = current_user.currency
    @new_product = true
  end

  def create
    #unless current_user.subscribed?
    #  redirect_to root_path
   #  end
    product = current_user.products.build(product_params)
    product.description = Sanitize.fragment(product.description, Sanitize::Config::BASIC)
    if product.save
      response = {product: product}
      response["twitter_url"] = twitter_url(product.name, product.slug)
      response["facebook_url"] = facebook_url(product.name, product.slug)
      response["edit_url"] =  user_product_path(product.id)
      response["symbol"] = product.price.symbol
      response["slug_url"] = product_slug_url(product.slug)
      render json: response and return
    end
    render json: {errors: product.errors}, status: :unprocessable_entity
  end

  def edit
    @product = Product.find(params[:id])
    is_owner?(@product.user_id)
    @twitter_url =  twitter_url(@product.name, @product.slug)
    @facebook_url =  facebook_url(@product.name, @product.slug)
    @slug = product_slug_url(@product.slug)
  end

  def update
    product = Product.find(params[:id])
    is_owner?(product.user_id)
    product.attributes = product_params
    product.description = Sanitize.fragment(product.description, Sanitize::Config::BASIC)
    #  price_currency:  @product.price.symbol }}
    if product.save
      response = {product: product}
      response["twitter_url"] = twitter_url(product.name, product.slug)
      response["facebook_url"] = facebook_url(product.name, product.slug)
      response["edit_url"] =  user_product_path(product.id)
      response["symbol"] = product.price.symbol
      response["slug_url"] = product_slug_url(product.slug)
      render json: response and return
    end
    render json: {}, status: :unprocessable_entity and return
  end

  def destroy
    product = Product.find(params[:id])
    is_owner?(product.user_id)
    product.destroy
    @id = params[:id]
    respond_to do |format|
      format.js {}
    end
  end

  def files
    if params[:provider] == 'dropbox'
      render json: Product.upload_from_url(params[:file][:name], params[:file][:link])
    else
      render json: Product.request(params[:name])
    end
  end

  def share
    @product = Product.find(params[:id])
    is_owner?(@product.user_id)
    @twitter =  twitter_url(@product.name, @product.slug)
    @facebook =  facebook_url(@product.name, @product.slug)
    @slug = product_slug_url(@product.slug)
    respond_to do |format|
    format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
    format.js
  end
end

def toggle_published
  product = Product.find(params[:id])
  is_owner?(product.user_id)
  product.toggle(:published)
  if product.save
    render json: {}, status: :ok and return
  end
  render json: {}, status: :unprocessable_entity
end

private
def product_params
  params.require(:product).permit(:name, :file_key, :price, :price_currency,
   :description, :preview, :sales_limit)
end

private
def is_owner?(product_id)
  if product_id != current_user.id
    render file: "public/500.html", status: :unauthorized
  end
end

private
def facebook_url(name, slug)
  URI.escape(
    "https://www.facebook.com/sharer/sharer.php?u=#{product_slug_url(slug)}&title=#{name}")
end

private
def twitter_url(name, slug)
  URI.escape(
    "https://twitter.com/intent/tweet?text=#{name} #{product_slug_url(slug)}")
end

def twitter_url(name, slug)
  URI.escape(
    "https://twitter.com/intent/tweet?text=#{name} #{product_slug_url(slug)}")
end
end

app/controllers/user/tools/emails_controller.rb
class User::Tools::EmailsController < User::BaseController

  def new
   @list = MailingList.find(params[:mailing_list_id])
   @email = MailingListEmail.new
 end

 def create
  # sanitize
  # format
  # save
  # call sidekiq send_emails
 end
end

app/views/user/products/_old_form.html.erb
<div class="timeline">
  <ul>
    <li class="upload-section" data-product-id="<%= @product.id %>">
      <div class="cbp_tmicon info animated bounceIn">
        <i class="fa fa-cloud-upload"></i> </div>
        <div class="cbp_tmlabel">
         <div class="upload-box <% if !@product.new_record? %>  hid <% end %>">
          <form action="https://<%= Rails.configuration.aws["bucket"] %>.s3.amazonaws.com" method="POST"
            enctype="multipart/form-data" class="direct-upload">
            <input type="hidden" name="success_action_status" value="201">
            <div class="overlay">
             <p> Drop product file here or click to select from your computer.</p>
             <input data-url="https://upandsell.s3.amazonaws.com/"
             id="product-upload-btn"
             type="file" name="product[file_js]" multiple="" class="fileInput" >
           </div>
           <div class="upload-box-inner">
            <i class="fa fa-file-o fa-5x"></i>
          </div>
        </form>
      </div>
      <div class="uploading-box <% if @product.new_record? %>  hid <% end%>">
        <div class="row">
          <div class="col-md-5">
            <p class="filename"><%= @product.file_name %></p>
          </div>
          <div class="col-md-5">
            <div class="progress hid">
              <div class="progress-bar" style="width: 0%;">
              </div>
            </div>
          </div>
          <div class="col-md-2">
            <a class="fileinput-button file-change btn btn-primary pull-right" data-text-type="change">Change</a>
          </div>
        </div>
      </div>
    </div>

  </li>

  <li class="info-section">

    <div class="cbp_tmicon info animated bounceIn"> <i class="fa fa-pencil"></i> </div>
    <div class="cbp_tmlabel">
     <div class="product-form <% unless  @product.new_record?  %>  hid <% end%>">
      <%= simple_form_for [:user, @product], html: { multipart: true, class: 'product' },
      remote: true, data: { type: :json }  do |f| %>

      <input id="file_key" class="filename" type="hidden" name="[product]file_key" value="<%= @product.file_key %>" />
      <%= f.input_field :price_currency, as: :hidden %>
      <%= token_tag nil %>

      <div class="form-group row <%= error_class(@product, 'name') %>">
       <div class="col-md-1">
          <input class="form-control input-lg text-center" placeholder="∞" />
        </div>

        <div class="col-md-8">
          <%= f.input_field :name, class: 'form-control', placeholder: "Product Name" %>
        </div>
        <div class="col-md-2">
         <div class="input-group <%= error_class(@product, 'price_cents') %>">
           <span id="currency"
           data-currency-symbols="[&quot;$&quot;,&quot;\u00a3&quot;,&quot;\u20ac&quot;]"
           data-currency-values="[&quot;usd&quot;,&quot;gbp&quot;,&quot;eur&quot;]"
           class="input-group-addon btn-preview btn-primary"><%= @product.price.symbol %></span>
           <%= f.input_field :price, class: 'form-control', placeholder: "2.00" %>
         </div>
       </div>
       <div class="col-md-1">
        <%= f.button :submit,  "Save",
        data: {disable_with: 'Saving...'}, class: 'btn btn-block btn-primary text-center' %>
      </div>
    </div>
<hr></hr>
    <div class="form-group row">

      <div class="col-md-4">

        <div class="upload-box-preview">
          <div class="overlay">
            <%= f.input_field :preview, id: 'file-input', accept: "image/*",
            class: 'btn-preview input-thumb fileInput' %>
          </div>
          <input type="hidden" id="local-preview-path" value="" />

          <div id="preview" class="upload-box-preview-inner"
          data-preview-url="<%= @product.preview.url if @product.id%>">
          <p>Click to set a preview image</p>
          <i class="fa fa-picture-o fa-5x"></i>
        </div>
      </div>
    </div>
    <div class="col-md-8">
     <%= f.input_field :description,
     class: 'form-control product-description',
      placeholder: "Product Description(optional)" %>
    </div>
  </div>
  <% end %>
</div>

<div class="show-product-box product_show <% if @product.new_record? %>  hid <% end%>">
  <div class="row">
   <div class="col-md-1 preview-product-image">
     <img class="product-image img-rounded"
     src="<%= @product.preview.thumb.url if @product.id%>"
     style="height: 60px; width: 60px;">
   </div>
   <div class="col-md-5">
    <p class="product-name"><%= @product.name %></p>
  </div>
  <div class="col-md-1 text-center">
    <p><b class="product-price">
      <%= humanized_money_with_symbol @product.price %>
    </b></p>
  </div>

  <div class="col-md-5 text-right">
    <% unless  @product.new_record?  %>
    <%= link_to "Delete", user_product_path(@product),
    method: :delete,
    class: "m-r-5 btn btn-danger", confirm: "Are you sure?" %>

    <%
    if @product.published
     btn_text = "Unpublish"
     btn_with = "Unpublishing..."
   else
    btn_text = "Publish"
    btn_with = "Publishing..."
  end
  %>
  <%= link_to btn_text, toggle_published_user_product_path(@product),
  remote: true,
  data: {with: btn_with},
  class: "m-r-5 btn btn-warning toggle-published" %>

  <% end %>
  <a class="edit-product btn btn-primary">Edit</a>
</div>
</div>
</div>


</div>
</li>
<li class="share-section">

  <div class="cbp_tmicon info animated bounceIn"> <i class="fa fa-share"></i> </div>
  <div class="cbp_tmlabel p-b-0">
    <div  class="share p-t-10 p-l-30 p-r-20 p-b-20 text-center">
     <h3> Share to your audience!</h3>
     <div class="share <% if  @product.new_record?  %>  hid <% end%>">
       <div class="row">
        <div class="col-md-6 col-md-offset-3 share-url">

          <div class="col-md-10 slug">
            <h4 id="js-slug"><%= @slug %></h4>
          </div>
          <div class="col-md-1"><a id="js-copy-to-clipboard"
            data-clipboard-target="js-slug"
            class="btn btn-info"
            href="#"><i class="fa fa-clipboard"></i></a></div>

            <div class="col-md-1"><a id="js-ext-link" class="btn btn-info"
              href="<%= @slug %>" target="_blank">
              <i class="fa  fa-external-link"></i></a></div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <a href=" javascript: void(0)"
              <% if @twitter_url %>
              onclick="window.open(
              '<%= @twitter_url %>',
              'tweet','toolbar=0,status=0,width=600,height=305')"
              <% end %>
              class="btn btn-social-twitter btn-lg">
              <i class="fui-twitter"></i>
              Tweet
            </a>

            <a href=" javascript: void(0)"
            <% if @facebook_url %>
            onclick="window.open(
            '<%= @facebook_url %>',
            'share','toolbar=0,status=0,width=600,height=305')"
            <% end %>
            class="btn btn-lg btn-social-facebook">
            <i class="fui-facebook"></i>
            Share
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
</li>

</ul>
<div class="clearfix"></div>
</ul>
</div>

app/views/user/products/_product.html.erb
<div id="js-p-<%= product.id %>" class="products-list-item" >
  <div class="item-preview">
   <%= image_tag product.preview.thumb %>
 </div>

 <div class="item-info">
  <a title="Click to edit" href="<%= edit_user_product_url(product) %>">
    <%= product.name %></a>
  </div>
  <div class="item-actions">
    <%= link_to share_user_product_path(product.id),  class:'btn-product-action',
    data: { toggle: 'modal', target: '#share-modal' }, remote: true do %>
    <i class="fa fa-share-alt"></i>
    <% end %>

    <%= link_to product_slug_path(product.slug), class: 'btn-product-action' do %>
    <i class="fa fa-link"></i>
    <% end %>
    <%= link_to user_product_path(product), method: :delete, remote: true,
    class: 'js-p-delete btn-product-action', data: {confirm: 'Are you sure?'} do %>
    <i class="fa fa-trash-o"></i>
    <% end %>

  </div>
  <div class="item-published">
    <div class="bootstrap-switch-square">
    <input  data-on-text="Yes" data-off-text="No"
     type="checkbox" class="js-p-published switch" data-toggle="switch"
    data-url="<%= toggle_published_user_product_url(product) %>"
    <% if product.published %>
    checked
    <% end %>
    >
  </div>
</div>
</div>

app/views/user/products/destroy.js.erb
$('#js-p-<%= escape_javascript(@id) %>').slideUp() //.remove();
Up.alert.open('Product was deleted.')

app/views/user/products/edit.html.erb
<% content_for(:page_title)  { "Edit #{@product.name}" } %>
<%- content_for :title  do %>
<i class="fa fa-lg icon-tag-2"></i>
Products / <span>Edit</span>
<% end %>
<div id="product-form-page">
<div id="js-product-form" class="product product-form">
  <%= render partial: "user/products/tabs/product_details" %>
</div>
</div>

app/views/user/products/index.html.erb
<% content_for(:page_title)  { "Products" } %>
<%- content_for :title  do %>
<i class="fa fa-lg icon-tag-2"></i>
Products
<% end %>
<div class="products-page-index">
  <div class="products-actions">
    <div>
      <% if current_user.subscribed? %>
      <%= link_to(new_user_product_path, class: 'btn-app') do %>
      <i class="fa fa-lg fa-plus"></i>
      New Product
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="products-list-legend">
    <div class="p-info">
      <b>Product Info</b> <small>(Click the name to Edit)</small>
    </div>
    <div class="p-published">
      <b>Published</b>
    </div>
  </div>
  <div class="products-list">
   <% if @products.blank? %>
   <div class="no-products">
     <p>No products yet</p>
     <% if current_user.subscribed? %>
     <p>
      <%= link_to "Add One Now",
      new_user_product_path, class: "btn-app" %>
    </p>
    <% end %>
  </div>
  <% else %>
  <%= render @products %>
  <% end %>
</div>
<% unless @products.blank? %>
<div class="products-pagination">
 <%= paginate @products %>
</div>
<% end %>
</div>
<%= render 'share' %>

app/views/user/products/new.html.erb
<% content_for(:page_title)  { "Add New Product" } %>
<%- content_for :title  do %>
<i class="fa fa-lg icon-tag-2"></i>
Products / <span>New</span>
<% end %>
<%= render partial: "form" %>