config/routes.rb
require 'sidekiq/web'
require 'split/dashboard'

Upandsell::Application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe'
  get '/users/auth/mailchimp/callback' => 'user/settings/integrations#create'
  get '/users/auth/createsend/callback' => 'user/settings/integrations#create'

  get '/auth/paypal' => 'user/settings/payments#paypal_connect', as: 'paypal_integration'
  get '/auth/paypal/callback' => 'user/settings/payments#paypal_callback', as: 'paypal_integration_callback'

  devise_for :users, controllers: {  omniauth_callbacks: 'omniauth_callbacks',
    confirmations: 'confirmations', registrations: "registrations" }

    devise_scope :user do
      delete "/logout" => "devise/sessions#destroy"
      get "/join"   => "registrations#new"
      get "/login" => "devise/sessions#new"
    end
 # Front-end
 root 'landing#index'
 get 'no-beta' => 'landing#beta'
 post 'beta_request' => 'landing#beta_request'
 get 'pricing' => 'site#pricing'
 get 'privacy' => 'site#privacy'
 get 'terms' => 'site#terms'
 get 'demo' => 'site#demo'

 # subscriptions emails
 get 'unsubscribe/u/:user/:type/:signature' => 'emails#unsubscribe_user',
 :as => 'unsubscribe_user'
 get 'confirm_unsubscribe/u/:user/:type/:signature' => 'emails#confirm_unsubscribe_user',
 :as => 'confirm_unsubscribe_user'
 get 'unsubscribe/o/:order/:signature' => 'emails#unsubscribe_order',
 :as => 'unsubscribe_order'
 get 'confirm_unsubscribe/o/:order/:signature' => 'emails#confirm_unsubscribe_order',
 :as => 'confirm_unsubscribe_order'
 get 'unsubscribed' => 'emails#unsubscribed'

  #product page
  get '/p/:slug' => 'products#show', :as => 'product_slug'

  #checkout
  post 'checkout/paypal' => 'checkouts#paypal'
  get 'checkout/pay_info' => 'checkouts#pay_info'
  get 'checkout/braintree_token' => 'checkouts#braintree_token'
  post 'checkout/pay' => 'checkouts#pay'
  post 'checkout/unsubscribe_order_updates' => 'checkouts#unsubscribe_order_updates'
  get 'checkout/check_payment' => 'checkouts#check_paypal_payment'
  post 'checkout/ipn' => 'checkouts#ipn'
  get 'download/p/:token' => 'checkouts#download', :as => 'download_product'
  post 'checkout/check_coupon' => 'checkouts#check_coupon'

  resources :products, only: [:show]  do
  #get 'paypal',  on: :member
end

namespace :user do
  root 'dashboard#index'
  post 'dashboard/to_admin' => 'dashboard#to_admin'
  get 'dashboard/metrics'  => 'dashboard#metrics'
  get 'dashboard/onload_metrics'  => 'dashboard#onload_metrics'
  get 'complete_signup' => 'settings/billings#new'

  resources :affiliations
  resources :products, except: [:show] do
    post 'upload'
    get 'toggle_published',  on: :member
    get 'share', on: :member
  end

  resources :orders, only: [:index] do
   get 'refund', on: :member
 end

 namespace :tools do
  resources :coupons, except: [:new]
  resources :serial_keys, except: [:new]
  resources :mailing_lists do
    get 'sync', on: :member
    get 'createsend_clients', on: :collection
    get 'createsend_lists', on: :collection
    post 'create_sync', on: :member
    post 'remove_sync', on: :member
    get 'search', on: :collection
    post 'send_email', on: :member
    post 'send_test_email', on: :member
    resource :emails
  end
end


get 'setup', to: 'setup#index'
get 'billing_details', to: 'setup#billing_details'
post 'billing_details', to: 'setup#save_billing_details'
get 'resend_email', to: 'setup#resend_email'
patch 'update_email', to: 'setup#update_email'

post 'products/files'  => 'products#files'

namespace :settings do
  resources :webhooks, except: [:new]
  resource :account, only: [:edit, :update]
  resource :payments, only: [:edit, :update] do
    get 'connect'
    get 'connect_callback'
  end
  resource :integrations, only: [:edit, :create]
  resource :emails, only: [:edit, :update]
  resource :billing, except: [:index] do
    get 'invoice/:id', to: 'billings#invoice', as: 'invoice_download'
    post 'apply_coupon'
  end
end
end
namespace :admin do
 mount Sidekiq::Web => 'sidekiq'

 root 'dashboard#index'
 resources :users, only: [:index,:show] do
  post 'switch'
end
resources :products, only: [:index,:show, :destroy]
resources :orders, only: [:index,:show]
resources :invoices, only: [:index,:show]

resources :emails, only: [:index, :create] do
  get 'send_test_email'
end
resources :affiliations, only: [:index]
end

match "/admin/split" => Split::Dashboard, :anchor => false, :via => [:get, :post], :constraints => lambda { |request|
  request.env['warden'].authenticated? # are we authenticated?
  request.env['warden'].authenticate! # authenticate if not already
  request.env['warden'].user.admin?
}

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_after_filter :intercom_rails_auto_include
  layout false

  def index
     @beta = true
    if !params[:nobeta].blank?
     @beta = false
    end
  end

  def beta
  end

end

app/views/landing/beta.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sell downloads and digital products easily - Up&amp;Sell.me</title>
  <meta name="description" content="Sell your music, videos, ebooks, software
  and other any downloadable products." />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "frontend", media: "all" %>
   <!--[if lte IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script>
        <![endif]-->
        <%= csrf_meta_tags %>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-54494496-1', 'auto');
          ga('send', 'pageview');
        </script>
      </head>
      <body class="home">
        <%= render partial: 'layouts/site/cookie_alert' %>
        <div id="wrap">
         <%= render partial: 'layouts/site/header' %>
         <div id="header">
          <div class="container">
            <div class="row">
              <div class="inner-header">
                <h1 class="animated fadeInUp">Sell your  digital products, easily.</h1>
                <h2 class="animated fadeInUp">Fastest way to sell music, ebooks, software
                  or any other downloadable product</h2>
                  <a class="btn-more hidden-animation" href="#checkout">Learn More</a>
                  <%= link_to "Get Started!", new_user_registration_path,
                  class: "btn-get-started hidden-animation" %>
                </div>
              </div>
              <div class="browser-preview-wrap">
                <div class="browser-preview hidden">
                  <div class="shadow-1"></div>
                  <div class="shadow-2"></div>
                  <%= image_tag 'browser_bar.png', class: 'browser-bar' %>
                  <%= image_tag 'dashboard.png', class: 'browser-tab' %>
                  <%= image_tag 'small_cloud_left_t.png', class: 'small-cloud-left-t animated pulse' %>
                  <%= image_tag 'small-cloud-left_b.png', class: 'small-cloud-left-b animated pulse' %>
                  <%= image_tag 'small_cloud_right.png', class: 'small-cloud-right animated pulse' %>
                </div>

              </div>
            </div>
            <%= image_tag 'bg_clouds_left.png', class: 'bg-clouds-left' %>
            <%= image_tag 'bg_clouds_right.png', class: 'bg-clouds-right' %>
          </div>
          <div id="checkout" class="checkout-section">
           <div class="container">
            <div class="section-text">
             <h3>Optimized
               Product Page</h3>
               <p>
                A clear, clean and simple landing page and checkout process are the
                secret sauce to sell effectively online.
                Clarity, cleanness and simplicity: these are the principles we put at
                the core of our service.              </p>
                <p>
                  Upload a product file, insert the details, share to your audience and
                  start selling in less than a minute.
                  Simple. Isn't it?
                </p>
                <p>
                 <a class="btn-trydemo" href="#">Try Demo</a>
               </p>
             </div>
             <div class="section-illustration">
               <div class="checkout-demo-box">
                 <%= image_tag 'mock_iphone.png', class: 'mock_iphone' %>
                 <%= image_tag 'checkout_mock.png', class: 'mock-checkout' %>
               </div>
             </div>
           </div>
         </div>

         <div class="payments-section">
           <div class="container">
            <div class="section-illustration">
             <%= image_tag 'payments_section.png', class: 'mock_iphone',
             alt: 'Supported Gateways' %>
           </div>
           <div class="section-text">
             <h3>Payment Gateways</h3>
             <p>
               Accept all major debit and credit cards and collect your payments
               without worries: we are integrated with Paypal and Paymill.
             </p>
             <p>
              You can attract customers from around the world and process up to 100
              currencies. Get safe online with secure payment systems (Verified by
              VISA and MasterCard SecureCode).
            </p>
          </div>

        </div>
      </div>
      <div class="features-section">
       <div class="container">
         <h4>Marketing Tools</h4>

         <div class="feature-box">
           <div class="feature-icon">
            <%= image_tag 'ml_integration_feature.png' %>
          </div>
          <h5>Mailchimp &amp; Campaign Monitor Sync</h5>
          <p>
            Connect Up&amp;Sell.me to your Mailchimp or Campaign Monitor account and
            start marketing your products. Create beautiful emails, send them to
            your current and prospective customers, and track everything related
            to your campaigns.   </p> </div>
            <div class="feature-box">
              <div class="feature-icon">
                <%= image_tag 'send_ml_feature.png' %>
              </div>
              <h5>Send Newsletter to your buyers</h5>
              <p>
                Thank them after sales, send regular
                updates and meaningful info about your products and services.
                Create contents that matter, and boost your revenue.
              </p>
            </div>
            <div class="feature-box">
              <div class="feature-icon">
                <%= image_tag 'coupons_feature.png' %>
              </div>
              <h5>Create Coupons and promo codes</h5>
              <p>
                Coupons are an effective way to promote your products and services
                online. Create discounts, define promotions, design viral offers and
                make your customers happy.
              </p>
            </div>

          </div>
        </div>
        <div class="teaser-section">
         <div class="container">
           <div class="head">
             <h5>Coming Soon</h5>
             <p>Facebook Advertise, Google AdWords, Twitter Advertising.
              Everything you need to plan your best marketing campaigns.</p>
            </div>
            <div class="ads-logos">
              <%= image_tag 'fb_ads.png', class: 'ad-logo' %>
              <%= image_tag 'adwords_ads.png', class: 'ad-logo' %>
              <%= image_tag 'twitter_ads.png', class: 'ad-logo' %>
            </div>
          </div>
        </div>
        <div class="pricing-section">
         <div class="container">
           <div class="head">
             <h6>Pricing</h6>
             <p>One edition. 30 days trial. 24.99$ per month. 24/7 customer service.
              Try our service, start selling and contact us at anytime for any support.</p>
            </div>
            <div class="pricing-plans">
              <div class="plan-blue">
               <div class="plan-tag-blue">
                <%= image_tag 'price_tag_blue.png' %>
                <h6 class="tag-head">Pro</h6>
                <span class="tag-currency">$</span><span class="tag-price">24</span>.99
                <div class="bottom-tag">
                  <p class="f-p">Free Trial</p>
                  <p class="s-p">30 days</p>
                </div>
              </div>
              <div class="plan-text-blue">
                <ul>
                  <li><span>lorem cieoe</span></li>
                  <li><span>lorem cieoe</span></li>
                  <li><span>lorem cieoe</span></li>
                  <li><span>lorem cieoe</span></li>
                </ul>
                <a href="#" class="btn-tag-blue">Sign up for trial</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="footer">
      <div class="wrap-footer">
        <div class="line-1">
          <div class="footer-brand">
            <%= link_to(root_path) do %>
            <%= image_tag "footer_logo.png" %>
            <% end %>
          </div>
          <div class="social-icons">
            <span>Follow us:</span>
            <a href="https://www.facebook.com/pages/UpSellme/590644707644241"
            class="icon-facebook"></a>
            <a href="https://twitter.com/upandsell_me" class="icon-twitter"></a>
          </div>
        </div>

        <div class="line-2">
          <div class="site-info">
            <p>Sell your digital products, easily.</p>
            <p>email: <a href="mailto:support@upandsell.me">info@upandsell.me</a></p>
          </div>

          <div class="site-links">
            <ul>
              <li>
                <%= link_to "terms of service |", terms_path %>
              </li>

              <li>
                <%= link_to "privacy policy", privacy_path %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "frontend"%>
  </body>
  </html>

app/views/landing/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sell downloads and digital products easily - Up&amp;Sell.me</title>
  <meta name="description" content="Sell your music, videos, ebooks, software
  and other any downloadable products." />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="verifyownership" content="184dd104cfdd87879fbc37c3349a1297" />
  <%= stylesheet_link_tag    "frontend", media: "all" %>
   <!--[if lte IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script>
        <![endif]-->
        <%= csrf_meta_tags %>
        <% if Rails.env == 'production' %>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-54494496-1', 'auto');
          ga('send', 'pageview');
        </script>
        <% end %>
      </head>
      <body class="home">
        <%= render partial: 'layouts/site/cookie_alert' %>
        <div id="wrap">
         <%= render partial: 'layouts/site/header' %>
         <div id="header">
          <div class="container">
            <div class="row">
              <div class="inner-header">
                <h1 class="animated fadeInUp">Easily sell your digital products</h1>
                <h2 class="animated fadeInUp">Fastest way to sell fonts, themes, templates, plugins, graphics and
                  other downloadable products</h2>
                  <%= link_to "Start For Free", join_path,
                  class: "btn-get-started hidden-animation" %>

                  <div class="beta-message hidden-animation">
                    <p><i class="fa fa-arrow-down"></i> Scroll to see all the features <i class="fa fa-arrow-down"></i></p>
                  </div>
                </div>
              </div>
              <div class="browser-preview-wrap">
                <div class="browser-preview hidden">
                  <div class="shadow-1"></div>
                  <div class="shadow-2"></div>
                  <%= image_tag 'browser_bar.png', class: 'browser-bar' %>
                  <%= image_tag 'dashboard.png', class: 'browser-tab' %>
                  <%= image_tag 'small_cloud_left_t.png', class: 'small-cloud-left-t animated pulse' %>
                  <%= image_tag 'small-cloud-left_b.png', class: 'small-cloud-left-b animated pulse' %>
                  <%= image_tag 'small_cloud_right.png', class: 'small-cloud-right animated pulse' %>
                </div>

              </div>
            </div>
            <%= image_tag 'bg_clouds_left.png', class: 'bg-clouds-left' %>
            <%= image_tag 'bg_clouds_right.png', class: 'bg-clouds-right' %>
          </div>
          <div id="checkout" class="checkout-section">
           <div class="container">
            <div class="section-text">
             <h3>Optimized
               Product Page</h3>
               <p>
                The secret of effective online selling lies in a clear,
                clean and simple landing page – and an easy checkout process.
                Clarity, cleanness and simplicity are the principles at the core of our service.
              </p>
              <p>
                Upload a product file, insert the details, share with your audience and
                start selling in less than a minute. Simple.
              </p>
              <p>
               <%= link_to 'Try Demo', demo_path, class: 'btn-trydemo',  target: '_blank' %>
             </p>
           </div>
           <div class="section-illustration">
             <div class="checkout-demo-box">
               <%= image_tag 'mock_iphone.png', class: 'mock_iphone' %>
               <%= image_tag 'checkout_mock.png', class: 'mock-checkout' %>
             </div>
           </div>
         </div>
       </div>

       <div class="payments-section">
         <div class="container">
          <div class="section-illustration">
           <%= image_tag 'payments_section.png', class: 'mock_iphone',
           alt: 'Supported Gateways' %>
         </div>
         <div class="section-text">
           <h3>Payment Gateways</h3>
           <p>
             We accept all major debit and credit cards to help you collect your payments
             without worries: we are integrated with PayPal, Stripe, PAYMILL and
             Braintree.
           </p>
           <p>
            You can attract customers from around the world and you can be paid
            in Dollars, Euros and Pounds. Be safe online with our secure payment
            systems (Verified by VISA and MasterCard SecureCode).
          </p>
        </div>

      </div>
    </div>
    <div class="features-section">
     <div class="container">
       <h4>Marketing Tools</h4>

       <div class="feature-box">
         <div class="feature-icon">
          <%= image_tag 'ml_integration_feature.png' %>
        </div>
        <h5>MailChimp &amp; Campaign Monitor Sync</h5>
        <p>
          Connect Up&amp;Sell.me to your MailChimp or Campaign Monitor account and
          start marketing your products. Create beautiful emails, send them to
          your current and prospective customers and track everything related
          to your campaigns.</p> </div>
          <div class="feature-box">
            <div class="feature-icon">
              <%= image_tag 'send_ml_feature.png' %>
            </div>
            <h5>Send newsletters to your buyers</h5>
            <p>
              Thank them after sales. Send regular
              updates and meaningful info about your products.
              Create contents that matters and boosts your revenue.
            </p>
          </div>
          <div class="feature-box">
            <div class="feature-icon">
              <%= image_tag 'coupons_feature.png' %>
            </div>
            <h5>Create coupons and promo codes</h5>
            <p>
              Coupons are an effective way to promote your products online.
              Create discounts, define promotions, design viral offers and
              make your customers happy.
            </p>
          </div>

        </div>
      </div>
          <!-- <div class="teaser-section">
           <div class="container">
             <div class="head">
               <h5>Coming Soon</h5>
               <p>Facebook Advertise, Google AdWords, Twitter Advertising.
                Everything you need to plan your best marketing campaigns.</p>
              </div>
              <div class="ads-logos">
                <%= image_tag 'fb_ads.png', class: 'ad-logo' %>
                <%= image_tag 'adwords_ads.png', class: 'ad-logo' %>
                <%= image_tag 'twitter_ads.png', class: 'ad-logo' %>
              </div>
            </div>
          </div> -->

          <div class="pricing-section">
           <div class="container">
             <div class="head">
               <h6>Pricing</h6>
               <p>One edition. <%= Rails.application.secrets.trial_days %> days free trial. 24.99€ per month. 24/7 customer service.
                Try our service, start selling and contact us at anytime you need support.</p>
              </div>
              <div class="pricing-plans">
                <div class="plan-blue">
                 <div class="plan-tag-blue">
                  <%= image_tag 'price_tag_blue.png' %>
                  <h6 class="tag-head">Pro</h6>
                  <span class="tag-currency">€</span><span class="tag-price">24</span>.99
                  <div class="bottom-tag">
                    <p class="f-p">Free Trial</p>
                    <p class="s-p"><%= Rails.application.secrets.trial_days %> days</p>
                  </div>
                </div>
                <div class="plan-text-blue">
                  <ul>
                    <li><span>Unlimited products</span></li>
                    <li><span>All Features Included</span></li>
                    <li><span>No Transaction Fees</span></li>
                  </ul>
                  <a href="/join" class="btn-tag-blue">Sign up for trial</a>
                </div>
              </div>
            </div>
          </div>
        </div>


      </div>
      <%= render :partial => 'layouts/site/footer' %>
      <%= javascript_include_tag "frontend"%>
      <% if Rails.env == 'production' %>
      <script>
        UserVoice=window.UserVoice||[];(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/ZrXL5QpQBVsHDvgKWSY1Q.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})();
        UserVoice.push(['set', {
          accent_color: '#4A4E62',
          trigger_color: 'white',
          trigger_background_color: '#addad5'
        }]);
        UserVoice.push(['identify', {}]);
        UserVoice.push(['addTrigger', { mode: 'contact', trigger_position: 'bottom-right' }]);
        UserVoice.push(['autoprompt', {}]);
      </script>
      <% end %>
    </body>
    </html>