config/routes.rb
require 'sidekiq/web'
require 'split/dashboard'

Upandsell::Application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe'
  get '/users/auth/mailchimp/callback' => 'user/settings/integrations#create'
  get '/users/auth/createsend/callback' => 'user/settings/integrations#create'

  get '/auth/paypal' => 'user/settings/payments#paypal_connect', as: 'paypal_integration'
  get '/auth/paypal/callback' => 'user/settings/payments#paypal_callback', as: 'paypal_integration_callback'

  devise_for :users, controllers: {  omniauth_callbacks: 'omniauth_callbacks',
    confirmations: 'confirmations', registrations: "registrations" }

    devise_scope :user do
      delete "/logout" => "devise/sessions#destroy"
      get "/join"   => "registrations#new"
      get "/login" => "devise/sessions#new"
    end
 # Front-end
 root 'landing#index'
 get 'no-beta' => 'landing#beta'
 post 'beta_request' => 'landing#beta_request'
 get 'pricing' => 'site#pricing'
 get 'privacy' => 'site#privacy'
 get 'terms' => 'site#terms'
 get 'demo' => 'site#demo'

 # subscriptions emails
 get 'unsubscribe/u/:user/:type/:signature' => 'emails#unsubscribe_user',
 :as => 'unsubscribe_user'
 get 'confirm_unsubscribe/u/:user/:type/:signature' => 'emails#confirm_unsubscribe_user',
 :as => 'confirm_unsubscribe_user'
 get 'unsubscribe/o/:order/:signature' => 'emails#unsubscribe_order',
 :as => 'unsubscribe_order'
 get 'confirm_unsubscribe/o/:order/:signature' => 'emails#confirm_unsubscribe_order',
 :as => 'confirm_unsubscribe_order'
 get 'unsubscribed' => 'emails#unsubscribed'

  #product page
  get '/p/:slug' => 'products#show', :as => 'product_slug'

  #checkout
  post 'checkout/paypal' => 'checkouts#paypal'
  get 'checkout/pay_info' => 'checkouts#pay_info'
  get 'checkout/braintree_token' => 'checkouts#braintree_token'
  post 'checkout/pay' => 'checkouts#pay'
  post 'checkout/unsubscribe_order_updates' => 'checkouts#unsubscribe_order_updates'
  get 'checkout/check_payment' => 'checkouts#check_paypal_payment'
  post 'checkout/ipn' => 'checkouts#ipn'
  get 'download/p/:token' => 'checkouts#download', :as => 'download_product'
  post 'checkout/check_coupon' => 'checkouts#check_coupon'

  resources :products, only: [:show]  do
  #get 'paypal',  on: :member
end

namespace :user do
  root 'dashboard#index'
  post 'dashboard/to_admin' => 'dashboard#to_admin'
  get 'dashboard/metrics'  => 'dashboard#metrics'
  get 'dashboard/onload_metrics'  => 'dashboard#onload_metrics'
  get 'complete_signup' => 'settings/billings#new'

  resources :affiliations
  resources :products, except: [:show] do
    post 'upload'
    get 'toggle_published',  on: :member
    get 'share', on: :member
  end

  resources :orders, only: [:index] do
   get 'refund', on: :member
 end

 namespace :tools do
  resources :coupons, except: [:new]
  resources :serial_keys, except: [:new]
  resources :mailing_lists do
    get 'sync', on: :member
    get 'createsend_clients', on: :collection
    get 'createsend_lists', on: :collection
    post 'create_sync', on: :member
    post 'remove_sync', on: :member
    get 'search', on: :collection
    post 'send_email', on: :member
    post 'send_test_email', on: :member
    resource :emails
  end
end


get 'setup', to: 'setup#index'
get 'billing_details', to: 'setup#billing_details'
post 'billing_details', to: 'setup#save_billing_details'
get 'resend_email', to: 'setup#resend_email'
patch 'update_email', to: 'setup#update_email'

post 'products/files'  => 'products#files'

namespace :settings do
  resources :webhooks, except: [:new]
  resource :account, only: [:edit, :update]
  resource :payments, only: [:edit, :update] do
    get 'connect'
    get 'connect_callback'
  end
  resource :integrations, only: [:edit, :create]
  resource :emails, only: [:edit, :update]
  resource :billing, except: [:index] do
    get 'invoice/:id', to: 'billings#invoice', as: 'invoice_download'
    post 'apply_coupon'
  end
end
end
namespace :admin do
 mount Sidekiq::Web => 'sidekiq'

 root 'dashboard#index'
 resources :users, only: [:index,:show] do
  post 'switch'
end
resources :products, only: [:index,:show, :destroy]
resources :orders, only: [:index,:show]
resources :invoices, only: [:index,:show]

resources :emails, only: [:index, :create] do
  get 'send_test_email'
end
resources :affiliations, only: [:index]
end

match "/admin/split" => Split::Dashboard, :anchor => false, :via => [:get, :post], :constraints => lambda { |request|
  request.env['warden'].authenticated? # are we authenticated?
  request.env['warden'].authenticate! # authenticate if not already
  request.env['warden'].user.admin?
}

end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < Admin::BaseController

  def index
    @invoices = SubscriptionInvoice.finalized.page(params[:page]).per(8)
  end

end

app/views/admin/invoices/index.html.erb
<% content_for(:page_title)  { "Fatture" } %>
<%- content_for :title  do %>
<i class="fa fa-lg icon-reciept-1"></i>
Orders  <span style="color: #888">(<%= SubscriptionInvoice.finalized.count %>)</span>
<% end %>

<div class="row p-b-15">
 <%= simple_form_for :invoices, url: user_orders_path,
 method: :get, html: { class: 'simple_form form-inline' } do |f|%>

 <div class="col-md-10">

  <div class="form-group">
    <input name="q" type="text" class="m-l-10 flat form-control" style="width: 350px;"
    placeholder="By Customer Email, id or product" value="<%= params[:q] %>">
  </div>
  <button type="submit" class="m-l-5 btn btn-primary">
    <i class="fa fa-filter"></i>
    Filter</button>
  </div>

  <% end %>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="grid simple ">

      <div class="grid-body ">


        <table class="table table-condensed ">
          <thead>
            <tr role="row">
              <th style="width:15%">N. #</th>
              <th style="width:18%"
              class="sorting_asc" rowspan="1" colspan="1">
              Dettagli Carta</th>
              <th style="width:6%"rowspan="1" colspan="1">
               Data</th>
               <th style="width:44%">Piano</th>
               <th style="width:6%">Amount</th>

               <th style="width:18%">date</th></tr>
             </thead>

             <tbody role="alert" aria-live="polite" aria-relevant="all">
               <% if @invoices.blank? %>
               <tr><td colspan="6"><p class="text-center text-muted">Nessuna fattura</p></td></tr>
               <% else %>

               <% @invoices.each do |subscription_invoice| %>
               <% if subscription_invoice.credit_note == false %>
               <tr>
                <td> <b>#<%= subscription_invoice.number %></b></td>
                <td>
                  <%= subscription_invoice.card_last4 %> -
                  <%= image_tag "cc_icons/#{subscription_invoice.card_brand.downcase}.png" %>
                </td>
                <td>
                  <%= subscription_invoice.finalized_at.to_time.strftime('%e %b %Y') %>
                </td>

                <td>Plan</td>

                <td><%= humanized_money_with_symbol Money.new(subscription_invoice.total, subscription_invoice.currency) %></td>

                <td>
                  <%= link_to "Invoice", invoice_download_user_settings_billing_path(subscription_invoice.id, format: :pdf), :class => "btn btn-primary" %>
                </td>
              </tr>
              <% else %>
              <tr>
                <td> <b>#<%= subscription_invoice.number %></b></td>
                <td>Credit note</td>
              </tr>
              <% end %>
              <% end %>
              <% end %>


            </tbody></table>

          </div>
        </div>
      </div>
    </div>


    <div class="row">
     <div class="col-md-offset-5 col-md-6">
       <%= paginate @invoices %>
     </div>
   </div>