config/routes.rb
require 'sidekiq/web'
require 'split/dashboard'

Upandsell::Application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe'
  get '/users/auth/mailchimp/callback' => 'user/settings/integrations#create'
  get '/users/auth/createsend/callback' => 'user/settings/integrations#create'

  get '/auth/paypal' => 'user/settings/payments#paypal_connect', as: 'paypal_integration'
  get '/auth/paypal/callback' => 'user/settings/payments#paypal_callback', as: 'paypal_integration_callback'

  devise_for :users, controllers: {  omniauth_callbacks: 'omniauth_callbacks',
    confirmations: 'confirmations', registrations: "registrations" }

    devise_scope :user do
      delete "/logout" => "devise/sessions#destroy"
      get "/join"   => "registrations#new"
      get "/login" => "devise/sessions#new"
    end
 # Front-end
 root 'landing#index'
 get 'no-beta' => 'landing#beta'
 post 'beta_request' => 'landing#beta_request'
 get 'pricing' => 'site#pricing'
 get 'privacy' => 'site#privacy'
 get 'terms' => 'site#terms'
 get 'demo' => 'site#demo'

 # subscriptions emails
 get 'unsubscribe/u/:user/:type/:signature' => 'emails#unsubscribe_user',
 :as => 'unsubscribe_user'
 get 'confirm_unsubscribe/u/:user/:type/:signature' => 'emails#confirm_unsubscribe_user',
 :as => 'confirm_unsubscribe_user'
 get 'unsubscribe/o/:order/:signature' => 'emails#unsubscribe_order',
 :as => 'unsubscribe_order'
 get 'confirm_unsubscribe/o/:order/:signature' => 'emails#confirm_unsubscribe_order',
 :as => 'confirm_unsubscribe_order'
 get 'unsubscribed' => 'emails#unsubscribed'

  #product page
  get '/p/:slug' => 'products#show', :as => 'product_slug'

  #checkout
  post 'checkout/paypal' => 'checkouts#paypal'
  get 'checkout/pay_info' => 'checkouts#pay_info'
  get 'checkout/braintree_token' => 'checkouts#braintree_token'
  post 'checkout/pay' => 'checkouts#pay'
  post 'checkout/unsubscribe_order_updates' => 'checkouts#unsubscribe_order_updates'
  get 'checkout/check_payment' => 'checkouts#check_paypal_payment'
  post 'checkout/ipn' => 'checkouts#ipn'
  get 'download/p/:token' => 'checkouts#download', :as => 'download_product'
  post 'checkout/check_coupon' => 'checkouts#check_coupon'

  resources :products, only: [:show]  do
  #get 'paypal',  on: :member
end

namespace :user do
  root 'dashboard#index'
  post 'dashboard/to_admin' => 'dashboard#to_admin'
  get 'dashboard/metrics'  => 'dashboard#metrics'
  get 'dashboard/onload_metrics'  => 'dashboard#onload_metrics'
  get 'complete_signup' => 'settings/billings#new'

  resources :affiliations
  resources :products, except: [:show] do
    post 'upload'
    get 'toggle_published',  on: :member
    get 'share', on: :member
  end

  resources :orders, only: [:index] do
   get 'refund', on: :member
 end

 namespace :tools do
  resources :coupons, except: [:new]
  resources :serial_keys, except: [:new]
  resources :mailing_lists do
    get 'sync', on: :member
    get 'createsend_clients', on: :collection
    get 'createsend_lists', on: :collection
    post 'create_sync', on: :member
    post 'remove_sync', on: :member
    get 'search', on: :collection
    post 'send_email', on: :member
    post 'send_test_email', on: :member
    resource :emails
  end
end


get 'setup', to: 'setup#index'
get 'billing_details', to: 'setup#billing_details'
post 'billing_details', to: 'setup#save_billing_details'
get 'resend_email', to: 'setup#resend_email'
patch 'update_email', to: 'setup#update_email'

post 'products/files'  => 'products#files'

namespace :settings do
  resources :webhooks, except: [:new]
  resource :account, only: [:edit, :update]
  resource :payments, only: [:edit, :update] do
    get 'connect'
    get 'connect_callback'
  end
  resource :integrations, only: [:edit, :create]
  resource :emails, only: [:edit, :update]
  resource :billing, except: [:index] do
    get 'invoice/:id', to: 'billings#invoice', as: 'invoice_download'
    post 'apply_coupon'
  end
end
end
namespace :admin do
 mount Sidekiq::Web => 'sidekiq'

 root 'dashboard#index'
 resources :users, only: [:index,:show] do
  post 'switch'
end
resources :products, only: [:index,:show, :destroy]
resources :orders, only: [:index,:show]
resources :invoices, only: [:index,:show]

resources :emails, only: [:index, :create] do
  get 'send_test_email'
end
resources :affiliations, only: [:index]
end

match "/admin/split" => Split::Dashboard, :anchor => false, :via => [:get, :post], :constraints => lambda { |request|
  request.env['warden'].authenticated? # are we authenticated?
  request.env['warden'].authenticate! # authenticate if not already
  request.env['warden'].user.admin?
}

end

app/controllers/user/setup_controller.rb
class User::SetupController < User::BaseController

  def index
    @email = current_user.confirmed?
    @payments = true if current_user.paypal || current_user.credit_card
  end

  def resend_email
    current_user.send_confirmation_instructions
    render json: {}, status: :ok and return
  end

  def update_email
    if current_user.update_without_password(email: params[:user][:email])
      current_user.send_confirmation_instructions
      render json: {}, status: :ok and return
    end
    render json: {}, status: :unprocessable_entity
  end

  def billing_details
  end

  def save_billing_details
    if billing_info_valid?
      current_user.attributes = billing_params.except(:stripe_token, :plan_type)
      if current_user.save && SubscriptionService.new(current_user).subscribe(params[:user][:stripe_token], params[:user][:plan_type].to_sym)
        render json: {url: user_setup_path}, status: :ok and return
      end
  end

  render json: {error: current_user.errors.full_messages}, status: :unprocessable_entity
end

  private
  def billing_info_valid?
    eu_countries= ['AT', 'BE', 'BG', 'CY', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'GB', 'CZ', 'RO', 'SK', 'SI', 'ES', 'SE', 'HU']

    info = billing_params

    [:stripe_token, :plan_type, :business_type, :country, :legal_name, :address,
      :zip_code, :city, :province].each do | e |
      return false if info[e].blank?
    end

    if info[:country] == 'IT' && info[:tax_code].blank?
      return false
    end

    if eu_countries.include?(info[:country]) && info[:business_type] == 'company'  && info[:tax_code].blank?
      return false
    end
    true
  end

  private
  def billing_params
    params.require(:user).permit(:stripe_token, :plan_type, :business_type, :country, :legal_name, :tax_code, :address, :zip_code, :city, :province)
  end
end

app/views/user/setup/tabs/_add_and_social.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 text-center">
    <p>Setup complete, add your first product and start selling with us.</p>
    <p><%= link_to(new_user_product_path, class: "btn btn-lg btn-primary") do %>
     Add New Product
     <% end %></p>
   </div>
 </div>

app/views/user/setup/tabs/_add_payment.html.erb
<div class="row">
  <div class="msg-payments">
    <p>Connect your Paypal account and/or your payments gateway to start receive money.</p>
    </div>
  </div>
<div class="actions-payments">
  <div class="action-paypal">
    <%= image_tag "paypal_setup.png" %>
    <p>
     <%= link_to "Connect", paypal_integration_path, class: 'btn btn-primary m-t-20' %>
   </p>
 </div>
 <div class="action-gateway">
  <%= image_tag "gateway_logo.png" %>
  <p>
   <%= link_to "Set Up", edit_user_settings_payments_path, class: 'btn btn-primary m-t-20' %>
 </p>
</div>

</div>

app/views/user/setup/tabs/_confirm_email.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 text-center">
    <p> We have sent an email to <b id="email"><%= current_user.email %></b>. </p>
    <p> Please click the link in the message to confirm your email andress.</p>
    <p>
      <%= link_to "Resend", user_resend_email_path, remote: true,
      data: { disable_with: "Resending..."},
      class: "btn-app", id: "resend-email" %>

      <a class="btn btn-default" id="change-email">Change Email</a></p>
    </div>
  </div>
  <div class="row">
    <div class="change-email">
     <%= form_tag user_update_email_path,
     disable_with: "Saving...", method: :patch, remote: true, id: 'js-email-box',
     class: "form-inline hid" do %>

     <div class="form-group" style="width:50%;">
      <input id="new-email" type="email" name="user[email]"
      style="width:100%;" class="form-control" placeholder="New Email">
    </div>
    <button type="submit" class="btn-app">Save</button>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2 text-center">
    <small>Make sure to check your junk or spam folder.
     The sender is <b>bot@upandsell.me</b></small>
   </div></div>